name: Frond-end - Push-to-EC2 CI

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      # - name: Build and Push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/front-end-clients:${{ github.sha }}

      - name: Build Docker image
        run: docker build -t front-end-clients:latest .
      - name: Tag Docker image
        run: docker tag front-end-clients:latest ${{ secrets.DOCKER_USERNAME }}/front-end-clients:latest
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/front-end-clients:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: "ec2-user"
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            docker stop front-end-clients || true
            docker rm front-end-clients || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/front-end-clients:latest
            docker run --restart=always -d --name front-end-clients -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/front-end-clients:latest
            docker cp apiClients/frontEnd/.env front-end-clients:/app

